#!/bin/sh
set -e
upstream=$1
: ${upstream:=origin}
: ${REPO:=git@github.com:g0v/hack.g0v.tw}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
  echo "not deploying"
  exit 1
fi
npm i
cp app/index.static.jade app/404.static.jade
rm -rf _public
# XXX: use --reference when not in shallow clone
#git clone $REPO --reference . -b gh-pages _public
git clone $REPO -b gh-pages _public

REV=`git describe --always`
BUILD=git-$REV ./node_modules/.bin/brunch b -o
# build twice, for static.html to propogate for now
BUILD=git-$REV ./node_modules/.bin/brunch b -o
cd _public
git add -A .
git commit-tree -m "regen for $REV" -p `git rev-parse HEAD` -p $REV `git write-tree` | xargs git reset --hard
git push origin gh-pages
cd ..
rm -f app/404.static.jade

# this is not automated with travis yet
if [ "x$FIREBASE" != "x" ]
then
	echo $FIREBASE
	lsc -j < etc/rules.ls | curl -X PUT -d @- $FIREBASE/.settings/rules.json?auth=$FIREBASE_SECRET
fi
