#!/bin/sh
set -e -x
git --version
upstream=$1
: ${upstream:=origin}
: ${REPO:=git@github.com:GITHUB_ACCOUNT/hackfoldr}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
  echo "not deploying"
  exit 1
fi
npm i
# for gh-pages
cp app/index.jade app/404.jade
rm -rf _public
# XXX: use --reference when not in shallow clone
#git clone $REPO --reference . -b gh-pages _public
git clone $REPO --depth 1 -b gh-pages _public

REV=`git describe --always`
GOOGLE_API_BROWSER_APPLICATION_KEY="AIzaSyCHm8NgD_p5F_-e7euH8BZiB4wSB8pOZ2A" BUILD=git-$REV ./node_modules/.bin/gulp --require LiveScript build --env production
cd _public
git fetch --depth 1 origin master:master
git add -A .
echo "regen for $REV" | git commit-tree `git write-tree` -p `git rev-parse HEAD` -p $REV | xargs git reset --hard
git push origin gh-pages
cd ..
rm -f app/404.jade

# this is not automated with travis yet
if [ "x$FIREBASE" != "x" ]
then
  echo $FIREBASE
  ./node_modules/.bin/lsc -j < etc/rules.ls | curl -X PUT -d @- $FIREBASE/.settings/rules.json?auth=$FIREBASE_SECRET
fi
